// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYS4brhsL8JQ7I2f-CqEgvpP3mq_vqaNM',
    appId: '1:321110104537:web:55e96b68cee4825a6261c8',
    messagingSenderId: '321110104537',
    projectId: 'managehome-139b0',
    authDomain: 'managehome-139b0.firebaseapp.com',
    databaseURL: 'https://managehome-139b0-default-rtdb.firebaseio.com',
    storageBucket: 'managehome-139b0.appspot.com',
    measurementId: 'G-FJXQ0179R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_vhhUNjiOjim7Wx_INRJASC1-xPFNldU',
    appId: '1:321110104537:android:be59d01e03a6903d6261c8',
    messagingSenderId: '321110104537',
    projectId: 'managehome-139b0',
    databaseURL: 'https://managehome-139b0-default-rtdb.firebaseio.com',
    storageBucket: 'managehome-139b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEzXaPsf5HCX5yBcx-aLSqa9eVQD746WA',
    appId: '1:321110104537:ios:08712068e3a4a53c6261c8',
    messagingSenderId: '321110104537',
    projectId: 'managehome-139b0',
    databaseURL: 'https://managehome-139b0-default-rtdb.firebaseio.com',
    storageBucket: 'managehome-139b0.appspot.com',
    iosClientId: '321110104537-jgprtml7gcromt42pek5b8srsdduodpf.apps.googleusercontent.com',
    iosBundleId: 'com.example.manageHouse',
  );
}
